project_id = "biccflgjfutwxppqhbjt"

[functions.requests]
verify_jwt = false

[functions.donors-nearby]
verify_jwt = false

[functions.escalate-emergency-alerts]
verify_jwt = false

[functions.send-emergency-alert]
verify_jwt = false

[functions.verify-phone]
verify_jwt = false
